### 1.Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program tocompute the mean and variance of the elements present in the array.Comment what the mean and variance of sample represents.

In [46]:
import numpy as np

def compute_mean(array):
    mean = np.sum(array) / len(array)
    return mean

def compute_sample_variance(array):
    mean = compute_mean(array)
    squared_diff = np.sum((array - mean) ** 2)
    variance = squared_diff / (len(array) - 1)
    return variance

def compute_population_variance(array):
    mean = compute_mean(array)
    squared_diff = np.sum((array - mean) ** 2)
    variance = squared_diff / len(array)
    return variance

def main():
    N = int(input("Enter the dimension of the vector: "))
    sample_vector = np.zeros(N)
    for i in range(N):
        sample_vector[i] = float(input(f"Enter element {i+1}: "))

    print("Sample Vector:", sample_vector)
    mean = compute_mean(sample_vector)
    sample_variance = compute_sample_variance(sample_vector)
    population_variance = compute_population_variance(sample_vector)

    print("Mean:", mean)
    print("Sample Variance:", sample_variance)
    print("Population Variance:", population_variance)

if __name__ == "__main__":
    main()

Enter the dimension of the vector: 9
Enter element 1: 4
Enter element 2: 5
Enter element 3: 6
Enter element 4: 7
Enter element 5: 8
Enter element 6: 9
Enter element 7: 9
Enter element 8: 8
Enter element 9: 4
Sample Vector: [4. 5. 6. 7. 8. 9. 9. 8. 4.]
Mean: 6.666666666666667
Sample Variance: 4.0
Population Variance: 3.5555555555555554


### 2.Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to compute the Covariance between them.Comment what Covariance between two vectors represents.

In [47]:
import numpy as np

In [48]:
def compute_covariance(vector1, vector2):
    covariance = np.cov(vector1, vector2)[0][1]
    return covariance

In [55]:
def main():
    M = int(input("Enter the dimension of the vectors: "))
    vector1 = np.random.rand(1, M)
    vector2 = np.random.rand(1, M)

    print("Vector 1:", vector1)
    print("Vector 2:", vector2)

    covariance = compute_covariance(vector1, vector2)
    print("Covariance between Vector 1 and Vector 2:", covariance)

In [58]:
if __name__ == "__main__":
    main()

Enter the dimension of the vectors: 4
Vector 1: [[0.29379488 0.09576954 0.3098351  0.00106487]]
Vector 2: [[0.690293   0.9440305  0.09341083 0.57115821]]
Covariance between Vector 1 and Vector 2: -0.02660300402146056


### 3.Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.Comment what the Correlation represents.

In [59]:
import numpy as np

In [60]:
def compute_correlation(vector1, vector2):
    correlation = np.corrcoef(vector1, vector2)[0][1]
    return correlation

In [63]:
def main():
    N = int(input("Enter the dimension of the vectors: "))
    vector1 = np.random.rand(1, N)
    vector2 = np.random.rand(1, N)

    print("Vector 1:", vector1)
    print("Vector 2:", vector2)
    
    correlation = compute_correlation(vector1, vector2)
    print("Correlation between Vector 1 and Vector 2:", correlation)

In [64]:
if __name__ == "__main__":
    main()

Enter the dimension of the vectors: 6
Vector 1: [[0.55567093 0.17384506 0.22069474 0.23836035 0.70177252 0.37429848]]
Vector 2: [[0.90781159 0.58471281 0.99092155 0.10741393 0.14587509 0.94546283]]
Correlation between Vector 1 and Vector 2: -0.19538554857043205


### 4.Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix.Comment on takeaways from these matrixes.

In [66]:
import numpy as np

In [67]:
def compute_covariance_matrix(matrix):
    covariance_matrix = np.cov(matrix)
    return covariance_matrix

In [68]:
def compute_correlation_matrix(matrix):
    correlation_matrix = np.corrcoef(matrix)
    return correlation_matrix

In [69]:
def main():
    M = int(input("Enter the dimension of the feature vector: "))
    N = int(input("Enter the number of samples: "))
    feature_matrix = np.random.rand(M, N)

    print("Feature Matrix:\n", feature_matrix)

    covariance_matrix = compute_covariance_matrix(feature_matrix)
    print("\nCovariance Matrix:\n", covariance_matrix)

    correlation_matrix = compute_correlation_matrix(feature_matrix)
    print("\nCorrelation Matrix:\n", correlation_matrix)

In [70]:
if __name__ == "__main__":
    main()

Enter the dimension of the feature vector: 2
Enter the number of samples: 4
Feature Matrix:
 [[0.5155178  0.8869871  0.72344682 0.7689119 ]
 [0.84158271 0.74897393 0.95048708 0.89946363]]

Covariance Matrix:
 [[ 0.02401556 -0.00417789]
 [-0.00417789  0.0074704 ]]

Correlation Matrix:
 [[ 1.        -0.3119166]
 [-0.3119166  1.       ]]
